version: '3.1'

services:
    app_v_0.5:
        image: 'cmsdemo_05:5'
        build: '.'
        ports:
            - 4000:80

# version: '3.6'

# services:   
#     kritner-website-web:
#         image: ${DOCKER_REGISTRY}/kritnerwebsite    
#         expose: - "5000"    
#         networks: - frontend    
#         restart: always    
#         container_name: kritnerwebsite_web  
#         kritner-website-nginx:    
#         image: nginx:latest    
#         ports:      - "80:80"
            
#         volumes:      - ../src/nginx/nginx.conf:/etc/nginx/nginx.conf    
#         depends_on: - kritner-website-web    
#         networks: - frontend    
#         restart: always    
#         container_name: kritnerwebsite_nginx
